name: Deploy CCI Actions Demo
on:
  push:
    branches:
      - master1
jobs:
  deploy_cci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set Node.js 16.x
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 16.x

#       - name: Install dependencies
#         run: npm ci

      - name: Rebuild the dist/ directory
        run: |
          npm install -g typescript
          npm i --save-dev @types/node
          npm install --verbose
          tsc
          #npm run build
          #npm run package
          ls -al ./
          #ls -al dist/
      - name: Install kubectl
        id: install-kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          curl -LO "https://dl.k8s.io/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"
          echo "$(<kubectl.sha256) kubectl" | sha256sum --check
          chmod +x kubectl
          mv ./kubectl /usr/local/bin
          kubectl version --client=true
      - name: deploy to cci
        uses: ./
        id: cci
        with:
          access_key: ${{ secrets.ACCESSKEY }}
          secret_key: ${{ secrets.SECRETACCESSKEY }}
          region: cn-north-4
          manifest: './deployment.yaml'
          images: 'swr.cn-north-4.myhuaweicloud.com/namespace/demo:v1.2'
      - name: List files in the repository
        run: |
          ls -al /usr/local/bin/
          cat ./deployment.yaml
          cci-iam-authenticator --help
