name: Deploy CCI Actions Demo
on:
  push:
    branches:
      - ncc
      
env:
  REGION_ID: cn-north-4                   # set this to your preferred huaweicloud region, e.g. cn-north-4
  ACCESS_KEY_ID: ${{ secrets.ACCESSKEY }}             # set this to your huaweicloud access-key-id
  ACCESS_KEY_SECRET: ${{ secrets.SECRETACCESSKEY }}               # set this to your huaweicloud access-key-secret
  SWR_ORGANIZATION:  hcloudcli   # set this to your huaweicloud SWR organization
  IMAGE_NAME: ccidemo # set this to your image name
      
      
jobs:
  deploy_cci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set Node.js 16.x
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 16.x

#       - name: Install dependencies
#         run: npm ci

      - name: Rebuild the dist/ directory
        run: |
          npm i -g @vercel/ncc
          npm install -g typescript
          npm i --save-dev @types/node
          npm install --verbose
          ncc build code/main.js -o dist --license licenses.txt
          # tsc
          #npm run build
          #npm run package
          ls -al ./
          ls -al dist/
      - name: List files in the repository
        run: |
          ls -al /usr/local/bin/
          cat ./deployment.yaml
          cat package.json
          cat package-lock.json
          cci-iam-authenticator --help
