name: Deploy CCI Actions Demo
on:
  push:
    branches:
      - master1
jobs:
  deploy_cci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set Node.js 16.x
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 16.x

#       - name: Install dependencies
#         run: npm ci

      - name: Rebuild the dist/ directory
        run: |
          npm install -g typescript
          npm i --save-dev @types/node
          npm install --verbose
          tsc
          #npm run build
          #npm run package
          ls -al ./
          #ls -al dist/
      - name: deploy to cci
        uses: ./
        id: cci
        with:
          access_key: ${{ secrets.ACCESSKEY }}
          secret_key: ${{ secrets.SECRETACCESSKEY }}
          region: cn-north-4
      - name: List files in the repository
        run: |
          ls -al /usr/local/bin/
          cci-iam-authenticator --help
